FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

RUN curl -sSL https://dtcooper.github.io/raspotify/key.asc | apt-key add -v - \
  && echo 'deb https://dtcooper.github.io/raspotify jessie main' | tee /etc/apt/sources.list.d/raspotify.list \
  && install_packages raspotify

CMD /bin/mkdir -m 0755 -p /var/cache/raspotify ; /bin/chown raspotify:raspotify /var/cache/raspotify

COPY start.sh /usr/src/

CMD bash /usr/src/start.sh
